# Video Games on Steam by genre, ESRB rating, and number of player recommendations

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# Import metacritic CSV
metacritic = pd.read_csv('../datasets_165618_377201_metacritic_games.csv')
metacritic

,game,platform,developer,genre,number_players,rating,release_date,positive_critics,neutral_critics,negative_critics,positive_users,neutral_users,negative_users,metascore,user_score
0,Portal 2,PC,Valve Software,Action,NaN,E10+,"Apr 18, 2011",51,1,0,1700,107,19,95,90
1,The Elder Scrolls V: Skyrim,PC,Bethesda Game Studios,Role-Playing,No Online Multiplayer,M,"Nov 10, 2011",32,0,0,1616,322,451,94,82
2,The Legend of Zelda: Ocarina of Time 3D,3DS,GREZZO,Miscellaneous,No Online Multiplayer,E10+,"Jun 19, 2011",84,1,0,283,20,5,94,90
3,Batman: Arkham City,PC,Rocksteady Studios,Action Adventure,NaN,T,"Nov 21, 2011",27,0,0,240,34,27,91,87
4,Super Mario 3D Land,3DS,Nintendo,Action,No Online Multiplayer,E,"Nov 13, 2011",81,1,0,251,39,11,90,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5694,Modern Combat: Blackout,Switch,Gameloft,Action,No Online Multiplayer,NaN,"Feb 14, 2019",0,5,2,1,0,1,53,57
5695,Fimbul,PS4,Zaxis,Action Adventure,No Online Multiplayer,NaN,"Feb 28, 2019",0,7,2,1,0,0,52,18
5696,Generation Zero,PC,Avalanche Studios,Action Adventure,Online Multiplayer,T,"Mar 26, 2019",1,11,6,5,2,6,50,57
5697,Vane,PS4,Friend & Foe,Adventure,No Online Multiplayer,E10+,"Jan 15, 2019",3,26,22,2,2,2,49,55
5698,Left Alive,PS4,"Square Enix, ilinx inc.",Action Adventure,No Online Multiplayer,M,"Mar 5, 2019",1,7,27,25,8,21,37,79

## Cleaning Metacritic

In [3]:
# Preserve the game, platformm genre, and ESRB rating columns
metacritic2 = metacritic[['game', 'platform','genre','rating']].copy()
metacritic2

,game,platform,genre,rating
0,Portal 2,PC,Action,E10+
1,The Elder Scrolls V: Skyrim,PC,Role-Playing,M
2,The Legend of Zelda: Ocarina of Time 3D,3DS,Miscellaneous,E10+
3,Batman: Arkham City,PC,Action Adventure,T
4,Super Mario 3D Land,3DS,Action,E
...,...,...,...,...
5694,Modern Combat: Blackout,Switch,Action,NaN
5695,Fimbul,PS4,Action Adventure,NaN
5696,Generation Zero,PC,Action Adventure,T
5697,Vane,PS4,Adventure,E10+
5698,Left Alive,PS4,Action Adventure,M

In [4]:
# Remove any games that are not on PC
metacritic_pc = metacritic2[metacritic2['platform'] == 'PC']
metacritic_pc

                             game platform             genre rating
0                        Portal 2       PC            Action   E10+
1     The Elder Scrolls V: Skyrim       PC      Role-Playing      M
3             Batman: Arkham City       PC  Action Adventure      T
5       Deus Ex: Human Revolution       PC            Action      M
7             Total War: Shogun 2       PC          Strategy      T
...                           ...      ...               ...    ...
5670    Jon Shafer's At the Gates       PC          Strategy    NaN
5685                   Jump Force       PC  Action Adventure      T
5688                       Anthem       PC      Role-Playing      T
5693                  Crackdown 3       PC  Action Adventure      M
5696              Generation Zero       PC  Action Adventure      T

[2138 rows x 4 columns]

In [5]:
# drop any duplicate rows
metacritic_pc = metacritic_pc.drop_duplicates()
metacritic_pc

                             game platform             genre rating
0                        Portal 2       PC            Action   E10+
1     The Elder Scrolls V: Skyrim       PC      Role-Playing      M
3             Batman: Arkham City       PC  Action Adventure      T
5       Deus Ex: Human Revolution       PC            Action      M
7             Total War: Shogun 2       PC          Strategy      T
...                           ...      ...               ...    ...
5670    Jon Shafer's At the Gates       PC          Strategy    NaN
5685                   Jump Force       PC  Action Adventure      T
5688                       Anthem       PC      Role-Playing      T
5693                  Crackdown 3       PC  Action Adventure      M
5696              Generation Zero       PC  Action Adventure      T

[2138 rows x 4 columns]

In [6]:
# Reset the index
metacritic_pc.reset_index(inplace=True)
metacritic_pc

      index                         game platform             genre rating
0         0                     Portal 2       PC            Action   E10+
1         1  The Elder Scrolls V: Skyrim       PC      Role-Playing      M
2         3          Batman: Arkham City       PC  Action Adventure      T
3         5    Deus Ex: Human Revolution       PC            Action      M
4         7          Total War: Shogun 2       PC          Strategy      T
...     ...                          ...      ...               ...    ...
2133   5670    Jon Shafer's At the Gates       PC          Strategy    NaN
2134   5685                   Jump Force       PC  Action Adventure      T
2135   5688                       Anthem       PC      Role-Playing      T
2136   5693                  Crackdown 3       PC  Action Adventure      M
2137   5696              Generation Zero       PC  Action Adventure      T

[2138 rows x 5 columns]

In [7]:
# Duplicate the newly-created index as a new column called 'id'
metacritic_pc['id'] = metacritic_pc.index
metacritic_pc

,index,game,platform,genre,rating,id
0,0,Portal 2,PC,Action,E10+,0
1,1,The Elder Scrolls V: Skyrim,PC,Role-Playing,M,1
2,3,Batman: Arkham City,PC,Action Adventure,T,2
3,5,Deus Ex: Human Revolution,PC,Action,M,3
4,7,Total War: Shogun 2,PC,Strategy,T,4
...,...,...,...,...,...,...
2133,5670,Jon Shafer's At the Gates,PC,Strategy,NaN,2133
2134,5685,Jump Force,PC,Action Adventure,T,2134
2135,5688,Anthem,PC,Role-Playing,T,2135
2136,5693,Crackdown 3,PC,Action Adventure,M,2136
2137,5696,Generation Zero,PC,Action Adventure,T,2137

In [8]:
# Delete the old index column and the platform column
metacritic_pc.drop(columns=['index', 'platform'], inplace=True)
metacritic_pc

                             game             genre rating    id
0                        Portal 2            Action   E10+     0
1     The Elder Scrolls V: Skyrim      Role-Playing      M     1
2             Batman: Arkham City  Action Adventure      T     2
3       Deus Ex: Human Revolution            Action      M     3
4             Total War: Shogun 2          Strategy      T     4
...                           ...               ...    ...   ...
2133    Jon Shafer's At the Gates          Strategy    NaN  2133
2134                   Jump Force  Action Adventure      T  2134
2135                       Anthem      Role-Playing      T  2135
2136                  Crackdown 3  Action Adventure      M  2136
2137              Generation Zero  Action Adventure      T  2137

[2138 rows x 4 columns]

In [9]:
# Rename the columns to make them more descriptive
metacritic_pc = metacritic_pc.rename(columns = {
    'game' : 'game_name',
    'rating' : 'esrb_rating',
})
metacritic_pc

                        game_name             genre esrb_rating    id
0                        Portal 2            Action        E10+     0
1     The Elder Scrolls V: Skyrim      Role-Playing           M     1
2             Batman: Arkham City  Action Adventure           T     2
3       Deus Ex: Human Revolution            Action           M     3
4             Total War: Shogun 2          Strategy           T     4
...                           ...               ...         ...   ...
2133    Jon Shafer's At the Gates          Strategy         NaN  2133
2134                   Jump Force  Action Adventure           T  2134
2135                       Anthem      Role-Playing           T  2135
2136                  Crackdown 3  Action Adventure           M  2136
2137              Generation Zero  Action Adventure           T  2137

[2138 rows x 4 columns]

In [10]:
## Import and clean Steam data
steam = pd.read_csv('../games-features.csv')
steam

,QueryID,ResponseID,QueryName,ResponseName,ReleaseDate,RequiredAge,DemoCount,DeveloperCount,DLCCount,Metacritic,...,LegalNotice,Reviews,SupportedLanguages,Website,PCMinReqsText,PCRecReqsText,LinuxMinReqsText,LinuxRecReqsText,MacMinReqsText,MacRecReqsText
0,10,10,Counter-Strike,Counter-Strike,Nov 1 2000,0,0,1,0,88,...,,,English French German Italian Spanish Simplifi...,None,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
1,20,20,Team Fortress Classic,Team Fortress Classic,Apr 1 1999,0,0,1,0,0,...,,,English French German Italian Spanish,None,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
2,30,30,Day of Defeat,Day of Defeat,May 1 2003,0,0,1,0,79,...,,,English French German Italian Spanish,http://www.dayofdefeat.com/,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
3,40,40,Deathmatch Classic,Deathmatch Classic,Jun 1 2001,0,0,1,0,0,...,,,English French German Italian Spanish,None,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
4,50,50,Half-Life: Opposing Force,Half-Life: Opposing Force,Nov 1 1999,0,0,1,0,0,...,,,English French German Korean,None,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13352,567660,567660,Baseball Riot,Baseball Riot,Jan 17 2017,0,0,1,0,0,...,Copyright (c) 2016 10tons Ltd.,,English**languages with full audio support,http://www.10tons.com/Game/baseball_riot.html,Minimum:OS: Windows XP / Vista / 7 / 8 / 10Pro...,,,,,
13353,567860,567860,Passage 4,Passage 4,Dec 13 2016,0,0,1,0,0,...,2016 copyright by netmin e.K.,,English* French Italian German* Spanish Dutch*...,http://www.libredia.com,Minimum:OS: Windows 2000/XP/Vista/7/8/10Proces...,,,,,
13354,567940,567940,Piximalism,Piximalism,Sep 26 2019,0,0,1,0,0,...,,,English,None,Minimum:OS: Microsoft(r) Windows(r) XP / Vista...,Recommended:OS: Microsoft(r) Windows(r) XP / V...,,,,
13355,568150,568150,Technoball,Technoball,Dec 12 2016,0,0,1,0,0,...,,,English**languages with full audio support,None,Minimum:OS: Windows 7 (64-bit)Processor: 2.5 G...,,,,,
13356,559250,559250,Ghostlight Manor,Ghostlight Manor,Dec 12 2016,0,0,1,0,0,...,,The real draw here is the gameplay Digital Fut...,English**languages with full audio support,http://digitalfuturelab.com/ghostlight/,Minimum:OS: Windows 7 64 bitProcessor: Intel C...,,,,Minimum:OS: Mac OSX 10.10+ 64 bitProcessor: In...,

In [11]:
# Retain only the ResponseName and RecommendationCount columns
steam_recs = steam[['ResponseName', 'RecommendationCount']].copy()
steam_recs

                    ResponseName  RecommendationCount
0                 Counter-Strike                68991
1          Team Fortress Classic                 2439
2                  Day of Defeat                 2319
3             Deathmatch Classic                  888
4      Half-Life: Opposing Force                 2934
...                          ...                  ...
13352              Baseball Riot                    0
13353                  Passage 4                    0
13354                 Piximalism                    0
13355                 Technoball                    0
13356           Ghostlight Manor                    0

[13357 rows x 2 columns]

In [12]:
# Remove duplicates
steam_recs = steam_recs.drop_duplicates()
steam_recs

                    ResponseName  RecommendationCount
0                 Counter-Strike                68991
1          Team Fortress Classic                 2439
2                  Day of Defeat                 2319
3             Deathmatch Classic                  888
4      Half-Life: Opposing Force                 2934
...                          ...                  ...
13352              Baseball Riot                    0
13353                  Passage 4                    0
13354                 Piximalism                    0
13355                 Technoball                    0
13356           Ghostlight Manor                    0

[13237 rows x 2 columns]

In [13]:
# Rename the columns
steam_recs = steam_recs.rename(columns= {
    'ResponseName':'game_name',
    'RecommendationCount':'num_recommendations'
})
steam_recs

                       game_name  num_recommendations
0                 Counter-Strike                68991
1          Team Fortress Classic                 2439
2                  Day of Defeat                 2319
3             Deathmatch Classic                  888
4      Half-Life: Opposing Force                 2934
...                          ...                  ...
13352              Baseball Riot                    0
13353                  Passage 4                    0
13354                 Piximalism                    0
13355                 Technoball                    0
13356           Ghostlight Manor                    0

[13237 rows x 2 columns]

In [16]:
# Reset the index
steam_recs = steam_recs.reset_index()
steam_recs

       index                  game_name  num_recommendations
0          0             Counter-Strike                68991
1          1      Team Fortress Classic                 2439
2          2              Day of Defeat                 2319
3          3         Deathmatch Classic                  888
4          4  Half-Life: Opposing Force                 2934
...      ...                        ...                  ...
13232  13352              Baseball Riot                    0
13233  13353                  Passage 4                    0
13234  13354                 Piximalism                    0
13235  13355                 Technoball                    0
13236  13356           Ghostlight Manor                    0

[13237 rows x 3 columns]

In [17]:
# Convert the new index into a column called 'id'. Will serve as the primary key
steam_recs['id'] = steam_recs.index
steam_recs

       index                  game_name  num_recommendations     id
0          0             Counter-Strike                68991      0
1          1      Team Fortress Classic                 2439      1
2          2              Day of Defeat                 2319      2
3          3         Deathmatch Classic                  888      3
4          4  Half-Life: Opposing Force                 2934      4
...      ...                        ...                  ...    ...
13232  13352              Baseball Riot                    0  13232
13233  13353                  Passage 4                    0  13233
13234  13354                 Piximalism                    0  13234
13235  13355                 Technoball                    0  13235
13236  13356           Ghostlight Manor                    0  13236

[13237 rows x 4 columns]

In [18]:
# Remove the old index columns
steam_recs = steam_recs.drop(columns = 'index')
steam_recs

                       game_name  num_recommendations     id
0                 Counter-Strike                68991      0
1          Team Fortress Classic                 2439      1
2                  Day of Defeat                 2319      2
3             Deathmatch Classic                  888      3
4      Half-Life: Opposing Force                 2934      4
...                          ...                  ...    ...
13232              Baseball Riot                    0  13232
13233                  Passage 4                    0  13233
13234                 Piximalism                    0  13234
13235                 Technoball                    0  13235
13236           Ghostlight Manor                    0  13236

[13237 rows x 3 columns]